name: Publish to PSGallery

on:
  workflow_dispatch:
    inputs:
      modulePath:
        description: "Provide the module path that includes .psd1"
        default: .\
        required: true
      NuGetApiKey:
        description: "Provide NuGetApiKey for your profile in PSGallery."
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish_module:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Publish to PSGallery
        uses: aammirmirza/Publish2PSGallery@PSGallery_v2
        with:
          NuGetApiKey: ${{ github.event.inputs.NuGetApiKey }}
          modulePath: ${{ github.event.inputs.modulePath }}
